version: '3.8'

services:
  # Aplicación Next.js
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/property_finder
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    depends_on:
      - postgres
      - redis
      - scraper-worker
    networks:
      - app-network

  # Servicio de base de datos PostgreSQL
  postgres:
    image: postgres:14
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=property_finder
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network

  # Servicio de Redis para caché y colas
  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - app-network

  # Worker para scraping en segundo plano
  scraper-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/property_finder
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  # Servicio de monitoreo
  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./server/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - app-network

  # Dashboard de monitoreo
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  prometheus-data:
  grafana-data:
