global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'scraper-worker'
    static_configs:
      - targets: ['scraper-worker:3001']

  - job_name: 'nextjs'
    static_configs:
      - targets: ['nextjs:3000']
